# Generated by Django 6.0.6 on 2026-09-03 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_advisor_status_user_phone'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='servicebooking',
            options={
                'ordering': [
                    '-booking_date',
                    'booking_time'
                ]
            },
        ),

        migrations.AddField(
            model_name='servicebooking',
            name='advisor',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    'advisor_status': 'APPROVED',
                    'role': 'ADVISOR'
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='advisor_bookings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddField(
            model_name='servicebooking',
            name='booking_time',
            field=models.CharField(
                choices=[
                    ('09:00', '09:00 AM - 10:00 AM'),
                    ('10:00', '10:00 AM - 11:00 AM'),
                    ('11:00', '11:00 AM - 12:00 PM'),
                    ('12:00', '12:00 PM - 01:00 PM'),
                    ('14:00', '02:00 PM - 03:00 PM'),
                    ('15:00', '03:00 PM - 04:00 PM'),
                    ('16:00', '04:00 PM - 05:00 PM'),
                    ('17:00', '05:00 PM - 06:00 PM'),
                ],
                default='09:00',
                max_length=5,
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customer_bookings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddConstraint(
            model_name='servicebooking',
            constraint=models.UniqueConstraint(
                fields=(
                    'advisor',
                    'booking_date',
                    'booking_time'
                ),
                name='unique_advisor_booking_slot',
            ),
        ),

    ]