# Generated by Django 6.0.6 on 2026-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_servicebooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='location',
            field=models.CharField(default='Kochi', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_letter',
            field=models.FileField(blank=True, null=True, upload_to='advisor_joining_letters/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('DEMO', 'Demo Payment'), ('RAZORPAY', 'Razorpay')], default='RAZORPAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
